# Generated by Django 5.1.2 on 2025-01-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_options_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
