# Generated by Django 5.1.2 on 2025-02-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_similarity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='quiz_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
