spring.application.name=Communication_Service

spring.data.mongodb.uri=mongodb://localhost:27017/communicationDB
spring.data.mongodb.database=communicationDB

spring.resources.add-mappings=false


server.port=8081
