# Generated by Django 5.1.2 on 2024-11-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_birth_date_user_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.AddField(
            model_name='company',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
