# Generated by Django 5.1.2 on 2024-11-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_company_location_company_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='as', max_length=255),
            preserve_default=False,
        ),
    ]
