# Generated by Django 5.1.2 on 2024-11-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_experience_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_obtained', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='awards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='companies_worked_at',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='users.certification'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='languages',
            field=models.ManyToManyField(blank=True, to='users.language'),
        ),
    ]
